Repository ontop/ontop, pull requests merged in 2023-07, with the labels that each got.

#702 Added partial RegEx support to SQLServer
  core/model/src/main/java/it/unibz/inf/ontop/model/term/functionsymbol/db/impl/DBRegexMatchAsLikeFunctionSymbolImpl.java
  core/model/src/main/java/it/unibz/inf/ontop/model/term/functionsymbol/db/impl/SQLServerDBIriStringResolverFunctionSymbolImpl.java
  db/rdb/src/main/java/it/unibz/inf/ontop/model/term/functionsymbol/db/impl/SQLServerDBFunctionSymbolFactory.java
  test/lightweight-tests/src/test/java/it/unibz/inf/ontop/docker/lightweight/mssql/BindWithFunctionsSQLServerTest.java
Labels: type: enhancement, status: fixed, w: db support

#706 Typing for math operators used in the mapping / lenses
  core/model/src/main/java/it/unibz/inf/ontop/injection/CoreSingletons.java
  core/model/src/main/java/it/unibz/inf/ontop/injection/impl/CoreSingletonsImpl.java
  core/model/src/main/java/it/unibz/inf/ontop/injection/impl/OntopModelModule.java
  core/model/src/main/java/it/unibz/inf/ontop/iq/type/NotYetTypedBinaryMathOperationTransformer.java
  core/model/src/main/java/it/unibz/inf/ontop/iq/type/impl/NotYetTypedBinaryMathOperationTransformerImpl.java
  core/model/src/main/java/it/unibz/inf/ontop/model/term/TermFactory.java
  core/model/src/main/java/it/unibz/inf/ontop/model/term/functionsymbol/db/DBFunctionSymbolFactory.java
  core/model/src/main/java/it/unibz/inf/ontop/model/term/functionsymbol/db/DBMathBinaryOperator.java
  core/model/src/main/java/it/unibz/inf/ontop/model/term/functionsymbol/db/impl/AbstractDBFunctionSymbolFactory.java
  core/model/src/main/java/it/unibz/inf/ontop/model/term/functionsymbol/db/impl/DefaultTypedDBMathBinaryOperator.java
  core/model/src/main/java/it/unibz/inf/ontop/model/term/functionsymbol/db/impl/DefaultUntypedDBMathBinaryOperator.java
  core/model/src/main/java/it/unibz/inf/ontop/model/term/impl/TermFactoryImpl.java
  core/model/src/main/resources/it/unibz/inf/ontop/injection/default.properties
  db/rdb/src/main/java/it/unibz/inf/ontop/dbschema/impl/LensNormalizerImpl.java
  db/rdb/src/main/java/it/unibz/inf/ontop/model/term/functionsymbol/db/impl/BigQueryDBFunctionSymbolFactory.java
  db/rdb/src/main/java/it/unibz/inf/ontop/model/term/functionsymbol/db/impl/MySQLDBFunctionSymbolFactory.java
  db/rdb/src/main/java/it/unibz/inf/ontop/model/term/functionsymbol/db/impl/OracleDBFunctionSymbolFactory.java
  db/rdb/src/main/java/it/unibz/inf/ontop/model/term/functionsymbol/db/impl/SnowflakeDBFunctionSymbolFactory.java
  db/rdb/src/main/java/it/unibz/inf/ontop/model/term/functionsymbol/db/impl/SparkSQLDBFunctionSymbolFactory.java
  mapping/sql/core/src/main/java/it/unibz/inf/ontop/spec/mapping/impl/SQLMappingExtractor.java
  mapping/sql/core/src/main/java/it/unibz/inf/ontop/spec/mapping/pp/impl/MetaMappingExpanderImpl.java
  test/lightweight-tests/src/test/java/it/unibz/inf/ontop/docker/lightweight/AbstractBindTestWithFunctions.java
  test/lightweight-tests/src/test/java/it/unibz/inf/ontop/docker/lightweight/bigquery/BindWithFunctionsBigQueryTest.java
  test/lightweight-tests/src/test/java/it/unibz/inf/ontop/docker/lightweight/mariadb/BindWithFunctionsMariaDBTest.java
  test/lightweight-tests/src/test/java/it/unibz/inf/ontop/docker/lightweight/mysql/BindWithFunctionsMySQLTest.java
  test/lightweight-tests/src/test/java/it/unibz/inf/ontop/docker/lightweight/oracle/BindWithFunctionsOracleTest.java
  test/lightweight-tests/src/test/java/it/unibz/inf/ontop/docker/lightweight/snowflake/BindWithFunctionsSnowflakeTest.java
  test/lightweight-tests/src/test/java/it/unibz/inf/ontop/docker/lightweight/spark/BindWithFunctionsSparkTest.java
  test/lightweight-tests/src/test/resources/books/athena/books-athena.obda
  test/lightweight-tests/src/test/resources/books/bigquery/books-bigquery.obda
  test/lightweight-tests/src/test/resources/books/books.obda
  test/lightweight-tests/src/test/resources/books/db2/books-db2.obda
  test/lightweight-tests/src/test/resources/books/dremio/books-dremio.obda
  test/lightweight-tests/src/test/resources/books/duckdb/books-duckdb.obda
  test/lightweight-tests/src/test/resources/books/oracle/books-oracle.obda
  test/lightweight-tests/src/test/resources/books/redshift/books-redshift.obda
  test/lightweight-tests/src/test/resources/books/snowflake/books-snowflake.obda
Labels: type: enhancement, status: fixed, w: db support

#705 Added new DateTime functions
  core/model/src/main/java/it/unibz/inf/ontop/model/term/TermFactory.java
  core/model/src/main/java/it/unibz/inf/ontop/model/term/functionsymbol/db/DBFunctionSymbolFactory.java
  core/model/src/main/java/it/unibz/inf/ontop/model/term/functionsymbol/db/impl/AbstractDBFunctionSymbolFactory.java
  core/model/src/main/java/it/unibz/inf/ontop/model/term/functionsymbol/db/impl/EqualsTrueDBIsTrueFunctionSymbolImpl.java
  core/model/src/main/java/it/unibz/inf/ontop/model/term/functionsymbol/db/impl/MockupDBFunctionSymbolFactory.java
  core/model/src/main/java/it/unibz/inf/ontop/model/term/functionsymbol/impl/DateTruncSPARQLFunctionSymbolImpl.java
  core/model/src/main/java/it/unibz/inf/ontop/model/term/functionsymbol/impl/FunctionSymbolFactoryImpl.java
  core/model/src/main/java/it/unibz/inf/ontop/model/term/impl/TermFactoryImpl.java
  core/model/src/main/java/it/unibz/inf/ontop/model/vocabulary/Ontop.java
  db/rdb/src/main/java/it/unibz/inf/ontop/model/term/functionsymbol/db/impl/AbstractSQLDBFunctionSymbolFactory.java
  db/rdb/src/main/java/it/unibz/inf/ontop/model/term/functionsymbol/db/impl/AthenaDBFunctionSymbolFactory.java
  db/rdb/src/main/java/it/unibz/inf/ontop/model/term/functionsymbol/db/impl/DB2DBFunctionSymbolFactory.java
  db/rdb/src/main/java/it/unibz/inf/ontop/model/term/functionsymbol/db/impl/DenodoDBFunctionSymbolFactory.java
  db/rdb/src/main/java/it/unibz/inf/ontop/model/term/functionsymbol/db/impl/DremioDBFunctionSymbolFactory.java
  db/rdb/src/main/java/it/unibz/inf/ontop/model/term/functionsymbol/db/impl/DuckDBDBFunctionSymbolFactory.java
  db/rdb/src/main/java/it/unibz/inf/ontop/model/term/functionsymbol/db/impl/H2SQLDBFunctionSymbolFactory.java
  db/rdb/src/main/java/it/unibz/inf/ontop/model/term/functionsymbol/db/impl/MySQLDBFunctionSymbolFactory.java
  db/rdb/src/main/java/it/unibz/inf/ontop/model/term/functionsymbol/db/impl/OracleDBFunctionSymbolFactory.java
  db/rdb/src/main/java/it/unibz/inf/ontop/model/term/functionsymbol/db/impl/PostgreSQLDBFunctionSymbolFactory.java
  db/rdb/src/main/java/it/unibz/inf/ontop/model/term/functionsymbol/db/impl/RedshiftDBFunctionSymbolFactory.java
  db/rdb/src/main/java/it/unibz/inf/ontop/model/term/functionsymbol/db/impl/SQLServerDBFunctionSymbolFactory.java
  db/rdb/src/main/java/it/unibz/inf/ontop/model/term/functionsymbol/db/impl/SnowflakeDBFunctionSymbolFactory.java
  db/rdb/src/main/java/it/unibz/inf/ontop/model/term/functionsymbol/db/impl/SparkSQLDBFunctionSymbolFactory.java
  db/rdb/src/main/java/it/unibz/inf/ontop/model/term/functionsymbol/db/impl/TrinoDBFunctionSymbolFactory.java
  test/docker-tests/src/test/java/it/unibz/inf/ontop/docker/db2/BindWithFunctionsDb2Test.java
  test/lightweight-tests/src/test/java/it/unibz/inf/ontop/docker/lightweight/AbstractBindTestWithFunctions.java
  test/lightweight-tests/src/test/java/it/unibz/inf/ontop/docker/lightweight/AbstractDockerRDF4JTest.java
  test/lightweight-tests/src/test/java/it/unibz/inf/ontop/docker/lightweight/athena/BindWithFunctionsAthenaTest.java
  test/lightweight-tests/src/test/java/it/unibz/inf/ontop/docker/lightweight/bigquery/BindWithFunctionsBigQueryTest.java
  test/lightweight-tests/src/test/java/it/unibz/inf/ontop/docker/lightweight/db2/BindWithFunctionsDB2Test.java
  test/lightweight-tests/src/test/java/it/unibz/inf/ontop/docker/lightweight/denodo/BindWithFunctionsDenodoTest.java
  test/lightweight-tests/src/test/java/it/unibz/inf/ontop/docker/lightweight/dremio/BindWithFunctionsDremioArrowFlightTest.java
  test/lightweight-tests/src/test/java/it/unibz/inf/ontop/docker/lightweight/dremio/BindWithFunctionsDremioTest.java
  test/lightweight-tests/src/test/java/it/unibz/inf/ontop/docker/lightweight/duckdb/BindWithFunctionsDuckDBTest.java
  test/lightweight-tests/src/test/java/it/unibz/inf/ontop/docker/lightweight/mariadb/BindWithFunctionsMariaDBTest.java
  test/lightweight-tests/src/test/java/it/unibz/inf/ontop/docker/lightweight/mssql/BindWithFunctionsSQLServerTest.java
  test/lightweight-tests/src/test/java/it/unibz/inf/ontop/docker/lightweight/mysql/BindWithFunctionsMySQLTest.java
  test/lightweight-tests/src/test/java/it/unibz/inf/ontop/docker/lightweight/oracle/BindWithFunctionsOracleTest.java
  test/lightweight-tests/src/test/java/it/unibz/inf/ontop/docker/lightweight/postgresql/BindWithFunctionsPostgreSQLTest.java
  test/lightweight-tests/src/test/java/it/unibz/inf/ontop/docker/lightweight/presto/BindWithFunctionsPrestoTest.java
  test/lightweight-tests/src/test/java/it/unibz/inf/ontop/docker/lightweight/redshift/BindWithFunctionsRedshiftTest.java
  test/lightweight-tests/src/test/java/it/unibz/inf/ontop/docker/lightweight/snowflake/BindWithFunctionsSnowflakeTest.java
  test/lightweight-tests/src/test/java/it/unibz/inf/ontop/docker/lightweight/spark/BindWithFunctionsSparkTest.java
  test/lightweight-tests/src/test/java/it/unibz/inf/ontop/docker/lightweight/trino/BindWithFunctionsTrinoTest.java
Labels: type: enhancement, status: fixed, w: sparql function

#709 Ignoring invalid mapping entries will now also ignore invalid lenses
  binding/rdf4j/src/test/java/it/unibz/inf/ontop/rdf4j/repository/IgnoreInvalidMappingEntriesTest.java
  binding/rdf4j/src/test/resources/ignore-invalid-mapping-entries/ignore-invalid.properties
  binding/rdf4j/src/test/resources/ignore-invalid-mapping-entries/lenses-column.json
  binding/rdf4j/src/test/resources/ignore-invalid-mapping-entries/lenses-table.json
  binding/rdf4j/src/test/resources/ignore-invalid-mapping-entries/lenses.json
  binding/rdf4j/src/test/resources/ignore-invalid-mapping-entries/test.db-extract.json
  binding/rdf4j/src/test/resources/ignore-invalid-mapping-entries/test.obda
  core/model/src/main/resources/property_description.json
  core/obda/src/main/java/it/unibz/inf/ontop/injection/OntopOBDASettings.java
  core/obda/src/main/java/it/unibz/inf/ontop/injection/impl/OntopOBDASettingsImpl.java
  core/obda/src/main/resources/it/unibz/inf/ontop/injection/obda-default.properties
  db/rdb/src/main/java/it/unibz/inf/ontop/dbschema/impl/LensMetadataProviderImpl.java
Labels: type: enhancement

#713 Composite UC inference now only considers variables that are related to the UC
  core/model/src/main/java/it/unibz/inf/ontop/iq/node/impl/ConstructionNodeImpl.java
Labels: type: performance, status: fixed

#715 Bugfix regarding handling of descending constants by flatten nodes
  core/model/src/main/java/it/unibz/inf/ontop/iq/exception/IntermediateQueryBuilderException.java
  core/model/src/main/java/it/unibz/inf/ontop/iq/node/impl/FlattenNodeImpl.java
  core/optimization/src/test/java/it/unibz/inf/ontop/iq/NormalizationTest.java
  core/optimization/src/test/java/it/unibz/inf/ontop/iq/optimizer/FlattenLiftTest.java
  test/docker-tests/src/test/java/it/unibz/inf/ontop/docker/postgres/nested/AbstractHrJsonTest.java
Labels: type: defect, status: fixed

#721 Fixed Old Version SQLServer LimitOffset normalization
  db/rdb/src/main/java/it/unibz/inf/ontop/generation/normalization/impl/SQLServerLimitOffsetOldVersionNormalizer.java
Labels: type: defect, status: fixed, w: db support
