Repository ontop/ontop, pull requests merged in 2023-04, with the labels that each got.

#630 XSD Cast Functions
  binding/owlapi/src/test/java/it/unibz/inf/ontop/owlapi/BindTest.java
  binding/rdf4j/src/test/java/it/unibz/inf/ontop/rdf4j/repository/CastPrimitiveDatatypesTest.java
  binding/rdf4j/src/test/resources/cast/cast-schema.sql
  binding/rdf4j/src/test/resources/cast/cast.obda
  core/model/src/main/java/it/unibz/inf/ontop/model/term/functionsymbol/db/DBFunctionSymbolFactory.java
  core/model/src/main/java/it/unibz/inf/ontop/model/term/functionsymbol/db/impl/AbstractDBFunctionSymbolFactory.java
  core/model/src/main/java/it/unibz/inf/ontop/model/term/functionsymbol/db/impl/MockupDBFunctionSymbolFactory.java
  core/model/src/main/java/it/unibz/inf/ontop/model/term/functionsymbol/db/impl/UnaryCastDBFunctionSymbolWithSerializerImpl.java
  core/model/src/main/java/it/unibz/inf/ontop/model/term/functionsymbol/impl/FunctionSymbolFactoryImpl.java
  core/model/src/main/java/it/unibz/inf/ontop/model/term/functionsymbol/impl/RDFDatatypeStringFunctionSymbolImpl.java
  core/model/src/main/java/it/unibz/inf/ontop/model/term/functionsymbol/impl/SPARQLCastFunctionSymbolImpl.java
  core/model/src/main/java/it/unibz/inf/ontop/model/type/TypeFactory.java
  db/rdb/src/main/java/it/unibz/inf/ontop/model/term/functionsymbol/db/impl/AbstractSQLDBFunctionSymbolFactory.java
  db/rdb/src/main/java/it/unibz/inf/ontop/model/term/functionsymbol/db/impl/DB2DBFunctionSymbolFactory.java
  db/rdb/src/main/java/it/unibz/inf/ontop/model/term/functionsymbol/db/impl/DenodoDBFunctionSymbolFactory.java
  db/rdb/src/main/java/it/unibz/inf/ontop/model/term/functionsymbol/db/impl/DremioDBFunctionSymbolFactory.java
  db/rdb/src/main/java/it/unibz/inf/ontop/model/term/functionsymbol/db/impl/DuckDBDBFunctionSymbolFactory.java
  db/rdb/src/main/java/it/unibz/inf/ontop/model/term/functionsymbol/db/impl/H2SQLDBFunctionSymbolFactory.java
  db/rdb/src/main/java/it/unibz/inf/ontop/model/term/functionsymbol/db/impl/MySQLDBFunctionSymbolFactory.java
  db/rdb/src/main/java/it/unibz/inf/ontop/model/term/functionsymbol/db/impl/OracleDBFunctionSymbolFactory.java
  db/rdb/src/main/java/it/unibz/inf/ontop/model/term/functionsymbol/db/impl/PostgreSQLDBFunctionSymbolFactory.java
  db/rdb/src/main/java/it/unibz/inf/ontop/model/term/functionsymbol/db/impl/PrestoDBFunctionSymbolFactory.java
  db/rdb/src/main/java/it/unibz/inf/ontop/model/term/functionsymbol/db/impl/SQLServerDBFunctionSymbolFactory.java
  db/rdb/src/main/java/it/unibz/inf/ontop/model/term/functionsymbol/db/impl/SnowflakeDBFunctionSymbolFactory.java
  db/rdb/src/main/java/it/unibz/inf/ontop/model/term/functionsymbol/db/impl/SparkSQLDBFunctionSymbolFactory.java
  db/rdb/src/main/java/it/unibz/inf/ontop/model/term/functionsymbol/db/impl/TrinoDBFunctionSymbolFactory.java
  db/rdb/src/main/java/it/unibz/inf/ontop/model/type/impl/DefaultSQLDBTypeFactory.java
  db/rdb/src/main/java/it/unibz/inf/ontop/model/type/impl/DuckDBDBTypeFactory.java
  db/rdb/src/main/java/it/unibz/inf/ontop/model/type/impl/H2SQLDBTypeFactory.java
  db/rdb/src/main/java/it/unibz/inf/ontop/model/type/impl/SQLServerDBTypeFactory.java
  db/rdb/src/main/java/it/unibz/inf/ontop/model/type/impl/SparkSQLDBTypeFactory.java
  db/rdb/src/main/java/it/unibz/inf/ontop/model/type/impl/TrinoDBTypeFactory.java
  test/lightweight-tests/src/test/java/it/unibz/inf/ontop/docker/lightweight/AbstractCastFunctionsTest.java
  test/lightweight-tests/src/test/java/it/unibz/inf/ontop/docker/lightweight/athena/CastAthenaTest.java
  test/lightweight-tests/src/test/java/it/unibz/inf/ontop/docker/lightweight/db2/CastDB2Test.java
  test/lightweight-tests/src/test/java/it/unibz/inf/ontop/docker/lightweight/denodo/CastDenodoTest.java
  test/lightweight-tests/src/test/java/it/unibz/inf/ontop/docker/lightweight/dremio/CastDremioTest.java
  test/lightweight-tests/src/test/java/it/unibz/inf/ontop/docker/lightweight/duckdb/CastDuckDBTest.java
  test/lightweight-tests/src/test/java/it/unibz/inf/ontop/docker/lightweight/mariadb/CastMariaDBTest.java
  test/lightweight-tests/src/test/java/it/unibz/inf/ontop/docker/lightweight/mssql/CastSQLServerTest.java
  test/lightweight-tests/src/test/java/it/unibz/inf/ontop/docker/lightweight/mysql/CastMySQLTest.java
  test/lightweight-tests/src/test/java/it/unibz/inf/ontop/docker/lightweight/oracle/CastOracleTest.java
  test/lightweight-tests/src/test/java/it/unibz/inf/ontop/docker/lightweight/postgresql/CastPostgreSQLTest.java
  test/lightweight-tests/src/test/java/it/unibz/inf/ontop/docker/lightweight/presto/CastPrestoTest.java
  test/lightweight-tests/src/test/java/it/unibz/inf/ontop/docker/lightweight/snowflake/CastSnowflakeTest.java
  test/lightweight-tests/src/test/java/it/unibz/inf/ontop/docker/lightweight/spark/CastSparkSQLTest.java
  test/lightweight-tests/src/test/java/it/unibz/inf/ontop/docker/lightweight/trino/CastTrinoTest.java
  test/sparql-compliance/src/test/java/it/unibz/inf/ontop/test/sparql/MemorySPARQLOntopQueryTest.java
  test/sparql-compliance/src/test/java/it/unibz/inf/ontop/test/sparql11/MemorySPARQL11QueryTest.java
Labels: type: enhancement, status: fixed, w: sparql function

#631 Ontop property to ignore invalid mapping entries
  binding/rdf4j/src/test/java/it/unibz/inf/ontop/rdf4j/repository/IgnoreInvalidMappingEntriesTest.java
  binding/rdf4j/src/test/resources/ignore-invalid-mapping-entries/ignore-invalid.properties
  binding/rdf4j/src/test/resources/ignore-invalid-mapping-entries/test.obda
  binding/rdf4j/src/test/resources/ignore-invalid-mapping-entries/test.sql
  core/model/src/main/resources/property_description.json
  core/obda/src/main/java/it/unibz/inf/ontop/injection/OntopOBDASettings.java
  core/obda/src/main/java/it/unibz/inf/ontop/injection/impl/OntopOBDASettingsImpl.java
  core/obda/src/main/resources/it/unibz/inf/ontop/injection/obda-default.properties
  mapping/sql/core/src/main/java/it/unibz/inf/ontop/spec/mapping/pp/impl/SQLPPMappingConverterImpl.java
Labels: type: enhancement, topic: mapping processing

#632 Fixed an issue with dremio, where VALUES clauses with integer constants caused the query to fail
  db/rdb/src/main/java/it/unibz/inf/ontop/generation/serializer/impl/DefaultSelectFromWhereSerializer.java
  db/rdb/src/main/java/it/unibz/inf/ontop/generation/serializer/impl/DremioSelectFromWhereSerializer.java
  test/lightweight-tests/src/test/java/it/unibz/inf/ontop/docker/lightweight/dremio/other/UnionWithValuesDremioArrowFlightTest.java
  test/lightweight-tests/src/test/java/it/unibz/inf/ontop/docker/lightweight/dremio/other/UnionWithValuesDremioTest.java
  test/lightweight-tests/src/test/resources/books/dremio/books-dremio-arrowflight.properties
  test/lightweight-tests/src/test/resources/books/dremio/books-dremio.properties
  test/lightweight-tests/src/test/resources/books/dremio/ontology-with-facts.ttl
Labels: type: defect, status: fixed, w: db support

#633 Implemented Flatten Lens for DuckDB
  db/rdb/src/main/java/it/unibz/inf/ontop/generation/serializer/impl/DuckDBSelectFromWhereSerializer.java
  db/rdb/src/main/java/it/unibz/inf/ontop/model/type/impl/DuckDBDBTypeFactory.java
  test/lightweight-tests/lightweight-db-test-images/duckdb/dbconstraints.db
  test/lightweight-tests/lightweight-db-test-images/duckdb/nested.sql
  test/lightweight-tests/lightweight-db-test-images/duckdb/ontop.db
  test/lightweight-tests/pom.xml
  test/lightweight-tests/src/test/java/it/unibz/inf/ontop/docker/lightweight/duckdb/NestedDataDuckDBTest.java
  test/lightweight-tests/src/test/resources/nested/duckdb/nested-duckdb.properties
  test/lightweight-tests/src/test/resources/nested/duckdb/nested-lenses-array.json
  test/lightweight-tests/src/test/resources/nested/duckdb/nested.obda
Labels: type: enhancement, status: fixed, w: db support

#637 Implemented a common base structure for FlattenNode implementation
  db/rdb/src/main/java/it/unibz/inf/ontop/generation/serializer/impl/DefaultSelectFromWhereSerializer.java
  db/rdb/src/main/java/it/unibz/inf/ontop/generation/serializer/impl/DremioSelectFromWhereSerializer.java
  db/rdb/src/main/java/it/unibz/inf/ontop/generation/serializer/impl/DuckDBSelectFromWhereSerializer.java
  db/rdb/src/main/java/it/unibz/inf/ontop/generation/serializer/impl/PostgresSelectFromWhereSerializer.java
  db/rdb/src/main/java/it/unibz/inf/ontop/generation/serializer/impl/SparkSQLSelectFromWhereSerializer.java
  db/rdb/src/main/java/it/unibz/inf/ontop/generation/serializer/impl/TrinoSelectFromWhereSerializer.java
  test/lightweight-tests/src/test/resources/nested/duckdb/nested-lenses-array.json
  test/lightweight-tests/src/test/resources/nested/spark/nested-lenses-array.json
  test/lightweight-tests/src/test/resources/nested/spark/nested-lenses-json.json
Labels: type: enhancement, w: db support

#636 Implemented Support for the Array/Object Access expression in Dremio
  core/model/src/main/java/it/unibz/inf/ontop/dbschema/QuotedIDFactory.java
  core/model/src/main/java/it/unibz/inf/ontop/dbschema/impl/SQLStandardQuotedIDFactory.java
  core/model/src/main/java/it/unibz/inf/ontop/model/term/functionsymbol/db/DBArrayObjectAccessFunctionSymbol.java
  core/model/src/main/java/it/unibz/inf/ontop/model/term/functionsymbol/db/DBFunctionSymbolFactory.java
  core/model/src/main/java/it/unibz/inf/ontop/model/term/functionsymbol/db/impl/AbstractDBFunctionSymbolFactory.java
  core/model/src/main/java/it/unibz/inf/ontop/model/term/functionsymbol/db/impl/DremioArrayAccessDBFunctionSymbol.java
  core/model/src/main/java/it/unibz/inf/ontop/model/term/impl/TermFactoryImpl.java
  db/rdb/src/main/java/it/unibz/inf/ontop/dbschema/impl/AbstractDBMetadataProvider.java
  db/rdb/src/main/java/it/unibz/inf/ontop/dbschema/impl/SQLServerQuotedIDFactory.java
  db/rdb/src/main/java/it/unibz/inf/ontop/dbschema/impl/json/JsonBasicOrJoinLens.java
  db/rdb/src/main/java/it/unibz/inf/ontop/generation/serializer/impl/DremioSelectFromWhereSerializer.java
  db/rdb/src/main/java/it/unibz/inf/ontop/model/term/functionsymbol/db/impl/DremioDBFunctionSymbolFactory.java
  db/rdb/src/main/java/it/unibz/inf/ontop/spec/sqlparser/ExpressionParser.java
  db/rdb/src/main/java/it/unibz/inf/ontop/spec/sqlparser/JSqlParserTools.java
  test/lightweight-tests/src/test/java/it/unibz/inf/ontop/docker/lightweight/dremio/NestedDataDremioTest.java
  test/lightweight-tests/src/test/resources/nested/dremio/nested-lenses-array.json
Labels: type: enhancement, status: fixed, w: db support

#638 Implemented FlattenLens for BigQuery
  db/rdb/src/main/java/it/unibz/inf/ontop/generation/serializer/impl/BigQuerySelectFromWhereSerializer.java
  db/rdb/src/main/java/it/unibz/inf/ontop/model/type/impl/BigQueryDBTypeFactory.java
  test/lightweight-tests/lightweight-db-test-images/bigquery/sql/nested.sql
  test/lightweight-tests/src/test/java/it/unibz/inf/ontop/docker/lightweight/bigquery/NestedDataBigQueryTest.java
  test/lightweight-tests/src/test/resources/nested/bigquery/nested-bigquery.properties
  test/lightweight-tests/src/test/resources/nested/bigquery/nested-lenses-array.json
Labels: type: enhancement, w: db support, w: datatype

#639 Implemented FlattenLens for MariaDB, MySQL and MSSQL
  db/rdb/src/main/java/it/unibz/inf/ontop/generation/serializer/impl/MariaDBSelectFromWhereSerializer.java
  db/rdb/src/main/java/it/unibz/inf/ontop/generation/serializer/impl/MySQLSelectFromWhereSerializer.java
  db/rdb/src/main/java/it/unibz/inf/ontop/generation/serializer/impl/SQLServerSelectFromWhereSerializer.java
  db/rdb/src/main/java/it/unibz/inf/ontop/model/term/functionsymbol/db/impl/MySQLDBFunctionSymbolFactory.java
  db/rdb/src/main/java/it/unibz/inf/ontop/model/term/functionsymbol/db/impl/SQLServerDBFunctionSymbolFactory.java
  db/rdb/src/main/java/it/unibz/inf/ontop/model/type/impl/MySQLDBTypeFactory.java
  db/rdb/src/main/resources/it/unibz/inf/ontop/injection/sql-default.properties
  test/lightweight-tests/lightweight-db-test-images/mariadb/Dockerfile
  test/lightweight-tests/lightweight-db-test-images/mariadb/sql/nested-mysql.sql
  test/lightweight-tests/lightweight-db-test-images/mssql/sql/nested-mssql.sql
  test/lightweight-tests/lightweight-db-test-images/mysql/sql/nested-mysql.sql
  test/lightweight-tests/src/test/java/it/unibz/inf/ontop/docker/lightweight/mariadb/NestedDataMariaDBTest.java
  test/lightweight-tests/src/test/java/it/unibz/inf/ontop/docker/lightweight/mssql/NestedDataSQLServerTest.java
  test/lightweight-tests/src/test/java/it/unibz/inf/ontop/docker/lightweight/mysql/NestedDataMySQLTest.java
  test/lightweight-tests/src/test/resources/nested/mariadb/nested-lenses.json
  test/lightweight-tests/src/test/resources/nested/mariadb/nested-mariadb.properties
  test/lightweight-tests/src/test/resources/nested/mssql/nested-lenses.json
  test/lightweight-tests/src/test/resources/nested/mssql/nested-mssql.properties
  test/lightweight-tests/src/test/resources/nested/mysql/nested-lenses.json
  test/lightweight-tests/src/test/resources/nested/mysql/nested-mysql.properties
Labels: type: enhancement, w: db support, w: datatype

#640 Implemented FlattenLens for Oracle DB
  db/rdb/src/main/java/it/unibz/inf/ontop/generation/normalization/impl/OracleExtraNormalizer.java
  db/rdb/src/main/java/it/unibz/inf/ontop/generation/normalization/impl/UnquoteFlattenResultsNormalizer.java
  db/rdb/src/main/java/it/unibz/inf/ontop/generation/serializer/impl/OracleSelectFromWhereSerializer.java
  db/rdb/src/main/java/it/unibz/inf/ontop/model/term/functionsymbol/db/impl/OracleDBFunctionSymbolFactory.java
  test/lightweight-tests/lightweight-db-test-images/oracle/sql/nested-oracle.sql
  test/lightweight-tests/src/test/java/it/unibz/inf/ontop/docker/lightweight/oracle/NestedDataOracleTest.java
  test/lightweight-tests/src/test/resources/nested/oracle/nested-lenses.json
  test/lightweight-tests/src/test/resources/nested/oracle/nested-oracle.properties
Labels: type: enhancement, w: db support, w: datatype

#641 Implemented FlattenLens for Redshift
  db/rdb/src/main/java/it/unibz/inf/ontop/generation/serializer/impl/PostgresSelectFromWhereSerializer.java
  db/rdb/src/main/java/it/unibz/inf/ontop/generation/serializer/impl/RedshiftSelectFromWhereSerializer.java
  db/rdb/src/main/java/it/unibz/inf/ontop/model/type/impl/RedshiftDBTypeFactory.java
  db/rdb/src/main/resources/it/unibz/inf/ontop/injection/sql-default.properties
  test/lightweight-tests/lightweight-db-test-images/redshift/sql/nested.sql
  test/lightweight-tests/src/test/java/it/unibz/inf/ontop/docker/lightweight/redshift/NestedDataRedshiftTest.java
  test/lightweight-tests/src/test/resources/nested/redshift/nested-lenses-array.json
  test/lightweight-tests/src/test/resources/nested/redshift/nested-redshift.properties
Labels: type: enhancement, w: db support, w: datatype

#643 Flatten Lens: Infer Unique and Foreign Key Constraints
  core/model/src/main/java/it/unibz/inf/ontop/iq/node/impl/FlattenNodeImpl.java
  db/rdb/src/main/java/it/unibz/inf/ontop/dbschema/impl/json/JsonFlattenLens.java
  db/rdb/src/test/java/it/unibz/inf/ontop/dbschema/NestedViewsPersonTest.java
Labels: type: enhancement, status: fixed, w: datatype

#646 Added STRING type to DuckDB
  db/rdb/src/main/java/it/unibz/inf/ontop/model/type/impl/DuckDBDBTypeFactory.java
  test/lightweight-tests/src/test/java/it/unibz/inf/ontop/docker/lightweight/duckdb/NestedDataDuckDBTest.java
Labels: type: enhancement, w: db support, w: datatype

#647 Replaced 'POSITION' function with 'INSTR' for SparkSQL
  db/rdb/src/main/java/it/unibz/inf/ontop/model/term/functionsymbol/db/impl/SparkSQLDBFunctionSymbolFactory.java
Labels: type: enhancement, status: fixed, w: db support
