Repository ontop/ontop, pull requests merged in 2023-08, with the labels that each got.

#726 Functional-dependency-based left-join optimization made more robust to nesting on the right
  binding/rdf4j/src/test/java/it/unibz/inf/ontop/rdf4j/repository/ProjectDenormalizedTest.java
  binding/rdf4j/src/test/resources/project-denormalized/db.sql
  binding/rdf4j/src/test/resources/project-denormalized/lenses.json
  binding/rdf4j/src/test/resources/project-denormalized/project.obda
  core/optimization/src/main/java/it/unibz/inf/ontop/iq/optimizer/impl/lj/AbstractLJTransformer.java
  core/optimization/src/main/java/it/unibz/inf/ontop/iq/optimizer/impl/lj/CardinalityInsensitiveJoinTransferLJOptimizer.java
Labels: type: enhancement, status: fixed

#732 Implemented transitive closure for lens FDs
  binding/rdf4j/src/test/resources/project-denormalized/lenses.json
  core/model/src/main/java/it/unibz/inf/ontop/iq/request/impl/FunctionalDependenciesImpl.java
  db/rdb/src/main/java/it/unibz/inf/ontop/dbschema/impl/json/JsonBasicOrJoinLens.java
  db/rdb/src/main/java/it/unibz/inf/ontop/dbschema/impl/json/JsonBasicOrJoinOrNestedLens.java
  db/rdb/src/main/java/it/unibz/inf/ontop/dbschema/impl/json/JsonFlattenLens.java
  db/rdb/src/main/java/it/unibz/inf/ontop/dbschema/impl/json/JsonLens.java
  db/rdb/src/main/java/it/unibz/inf/ontop/dbschema/impl/json/JsonSQLLens.java
  db/rdb/src/main/java/it/unibz/inf/ontop/dbschema/impl/json/JsonUnionLens.java
Labels: type: enhancement

#744 Implemented option to expose system tables
  core/model/src/main/resources/property_description.json
  core/obda/src/main/java/it/unibz/inf/ontop/injection/OntopOBDASettings.java
  core/obda/src/main/java/it/unibz/inf/ontop/injection/impl/OntopOBDASettingsImpl.java
  core/obda/src/main/resources/it/unibz/inf/ontop/injection/obda-default.properties
  db/rdb/src/main/java/it/unibz/inf/ontop/dbschema/impl/AbstractDBMetadataProvider.java
  db/rdb/src/main/java/it/unibz/inf/ontop/dbschema/impl/AthenaDBMetadataProvider.java
  db/rdb/src/main/java/it/unibz/inf/ontop/dbschema/impl/DremioDBMetadataProvider.java
  db/rdb/src/main/java/it/unibz/inf/ontop/dbschema/impl/OracleDBMetadataProvider.java
  db/rdb/src/main/java/it/unibz/inf/ontop/dbschema/impl/PostgreSQLDBMetadataProvider.java
  db/rdb/src/main/java/it/unibz/inf/ontop/dbschema/impl/SparkSQLDBMetadataProvider.java
Labels: type: enhancement, status: fixed, w: db support

#745 Fixed the implementation of the Redshift REGEXP_MATCH_3 function
  db/rdb/src/main/java/it/unibz/inf/ontop/model/term/functionsymbol/db/impl/RedshiftDBFunctionSymbolFactory.java
Labels: type: defect, status: fixed, w: db support

#746 Option to disable registering custom SPARQL aggregation functions
  core/kg-query/src/main/java/it/unibz/inf/ontop/injection/OntopKGQuerySettings.java
  core/kg-query/src/main/java/it/unibz/inf/ontop/injection/impl/OntopKGQuerySettingsImpl.java
  core/kg-query/src/main/java/it/unibz/inf/ontop/query/translation/impl/RDF4JQueryTranslatorImpl.java
  core/kg-query/src/main/resources/it/unibz/inf/ontop/injection/kg-query-default.properties
  core/model/src/main/resources/property_description.json
  core/obda/src/main/java/it/unibz/inf/ontop/injection/impl/OntopOBDASettingsImpl.java
  engine/system/sql/core/src/main/java/it/unibz/inf/ontop/injection/impl/OntopStandaloneSQLSettingsImpl.java
Labels: type: enhancement, status: fixed
