Repository ontop/ontop, pull requests merged in 2023-09, with the labels that each got.

#752 New left-join optimization: prune the right child when unused and cardinality doesn't matter
  core/optimization/src/main/java/it/unibz/inf/ontop/iq/optimizer/impl/lj/CardinalityInsensitiveLJPruningOptimizer.java
  core/optimization/src/main/java/it/unibz/inf/ontop/iq/optimizer/impl/lj/DefaultCompositeLeftJoinIQOptimizer.java
  core/optimization/src/main/resources/it/unibz/inf/ontop/injection/optimization-default.properties
  core/optimization/src/test/java/it/unibz/inf/ontop/iq/executor/LeftJoinOptimizationTest.java
Labels: type: enhancement, status: fixed

#753 Extract user, group and role information from HTTP headers
  binding/rdf4j/src/main/java/it/unibz/inf/ontop/rdf4j/predefined/impl/OntopRDF4JPredefinedQueryEngineImpl.java
  client/cli/src/test/java/it/unibz/inf/ontop/cli/AbstractOntopEndpointWithAccessControlTest.java
  client/cli/src/test/java/it/unibz/inf/ontop/cli/OntopEndpointWithAccessControlInLensTest.java
  client/cli/src/test/java/it/unibz/inf/ontop/cli/OntopEndpointWithAccessControlInMappingTest.java
  client/cli/src/test/resources/books/exampleBooks-access-control-in-lens.obda
  client/cli/src/test/resources/books/exampleBooks-access-control-in-mapping.obda
  client/cli/src/test/resources/books/exampleBooks-access-control-lenses.json
  client/cli/src/test/resources/books/exampleBooks-access-control.properties
  core/model/src/main/java/it/unibz/inf/ontop/evaluator/QueryContext.java
  core/model/src/main/java/it/unibz/inf/ontop/evaluator/impl/QueryContextImpl.java
  core/model/src/main/java/it/unibz/inf/ontop/injection/OntopModelSettings.java
  core/model/src/main/java/it/unibz/inf/ontop/injection/impl/OntopModelModule.java
  core/model/src/main/java/it/unibz/inf/ontop/injection/impl/OntopModelSettingsImpl.java
  core/model/src/main/java/it/unibz/inf/ontop/model/term/TermFactory.java
  core/model/src/main/java/it/unibz/inf/ontop/model/term/functionsymbol/FunctionSymbolFactory.java
  core/model/src/main/java/it/unibz/inf/ontop/model/term/functionsymbol/db/AuthorizationFunctionSymbol.java
  core/model/src/main/java/it/unibz/inf/ontop/model/term/functionsymbol/db/BooleanAuthorizationFunctionSymbol.java
  core/model/src/main/java/it/unibz/inf/ontop/model/term/functionsymbol/db/DBFunctionSymbolFactory.java
  core/model/src/main/java/it/unibz/inf/ontop/model/term/functionsymbol/db/impl/AbstractBooleanAuthorizationFunctionSymbol.java
  core/model/src/main/java/it/unibz/inf/ontop/model/term/functionsymbol/db/impl/AbstractDBAuthorizationFunctionSymbol.java
  core/model/src/main/java/it/unibz/inf/ontop/model/term/functionsymbol/db/impl/MockupDBFunctionSymbolFactory.java
  core/model/src/main/java/it/unibz/inf/ontop/model/term/functionsymbol/db/impl/OntopContainsRoleOrGroupFunctionSymbol.java
  core/model/src/main/java/it/unibz/inf/ontop/model/term/functionsymbol/db/impl/OntopUserFunctionSymbolImpl.java
  core/model/src/main/java/it/unibz/inf/ontop/model/term/functionsymbol/impl/FunctionSymbolFactoryImpl.java
  core/model/src/main/java/it/unibz/inf/ontop/model/term/functionsymbol/impl/IdentityFunctionSymbol.java
  core/model/src/main/java/it/unibz/inf/ontop/model/term/impl/TermFactoryImpl.java
  core/model/src/main/resources/it/unibz/inf/ontop/injection/default.properties
  core/model/src/main/resources/property_description.json
  core/optimization/src/main/java/it/unibz/inf/ontop/injection/impl/OntopOptimizationModule.java
  core/optimization/src/main/java/it/unibz/inf/ontop/iq/optimizer/AuthorizationFunctionEvaluator.java
  core/optimization/src/main/java/it/unibz/inf/ontop/iq/optimizer/GeneralStructuralAndSemanticIQOptimizer.java
  core/optimization/src/main/java/it/unibz/inf/ontop/iq/optimizer/impl/AuthorizationFunctionEvaluatorImpl.java
  core/optimization/src/main/java/it/unibz/inf/ontop/iq/optimizer/impl/GeneralStructuralAndSemanticIQOptimizerImpl.java
  core/optimization/src/main/resources/it/unibz/inf/ontop/injection/optimization-default.properties
  db/rdb/src/main/java/it/unibz/inf/ontop/model/term/functionsymbol/db/impl/AbstractSQLDBFunctionSymbolFactory.java
  db/rdb/src/test/java/it/unibz/inf/ontop/spec/sqlparser/ExpressionParserTest.java
  engine/reformulation/core/src/main/java/it/unibz/inf/ontop/answering/reformulation/QueryCache.java
  engine/reformulation/core/src/main/java/it/unibz/inf/ontop/answering/reformulation/QueryReformulator.java
  engine/reformulation/core/src/main/java/it/unibz/inf/ontop/answering/reformulation/impl/DummyQueryCache.java
  engine/reformulation/core/src/main/java/it/unibz/inf/ontop/answering/reformulation/impl/GuiceBasedQueryCache.java
  engine/reformulation/core/src/main/java/it/unibz/inf/ontop/answering/reformulation/impl/QuestQueryProcessor.java
  engine/reformulation/core/src/main/java/it/unibz/inf/ontop/answering/reformulation/impl/ToFullNativeQueryReformulator.java
  engine/reformulation/core/src/main/java/it/unibz/inf/ontop/injection/OntopReformulationSettings.java
  engine/reformulation/core/src/main/resources/it/unibz/inf/ontop/injection/reformulation-default.properties
  engine/system/core/src/main/java/it/unibz/inf/ontop/answering/connection/impl/Evaluator.java
  engine/system/core/src/main/java/it/unibz/inf/ontop/answering/connection/impl/QuestStatement.java
  engine/system/core/src/main/java/it/unibz/inf/ontop/query/resultset/impl/DefaultDescribeGraphResultSet.java
  engine/system/sql/core/src/main/java/it/unibz/inf/ontop/injection/impl/OntopStandaloneSQLSettingsImpl.java
  engine/system/sql/core/src/test/java/it/unibz/inf/ontop/answering/reformulation/OfflineOnlineMarriageTest.java
Labels: type: enhancement, status: fixed

#756 Distinct nodes: improve unique constraint and variable non requirement inference
  core/model/src/main/java/it/unibz/inf/ontop/iq/node/impl/DistinctNodeImpl.java
  core/model/src/main/java/it/unibz/inf/ontop/iq/node/impl/ExtensionalDataNodeImpl.java
  core/model/src/main/java/it/unibz/inf/ontop/iq/node/impl/LeftJoinNodeImpl.java
  core/model/src/main/resources/property_description.json
  core/optimization/src/test/java/it/unibz/inf/ontop/iq/NormalizationTest.java
  core/optimization/src/test/java/it/unibz/inf/ontop/iq/executor/FunctionalDependencyTest.java
  core/optimization/src/test/java/it/unibz/inf/ontop/iq/executor/LeftJoinOptimizationTest.java
  core/optimization/src/test/java/it/unibz/inf/ontop/iq/optimizer/FunctionalDependencyInferenceTest.java
Labels: type: enhancement

#755 Simplify Conjunctions and Disjunctions of Equalities
  binding/rdf4j/src/test/java/it/unibz/inf/ontop/rdf4j/repository/BooleanOperationSimplifierTest.java
  binding/rdf4j/src/test/resources/boolean-operation-simplifier/boolean-operation-simplifier.obda
  binding/rdf4j/src/test/resources/boolean-operation-simplifier/boolean-operation-simplifier.sql
  core/model/src/main/java/it/unibz/inf/ontop/model/term/functionsymbol/db/DBFunctionSymbolFactory.java
  core/model/src/main/java/it/unibz/inf/ontop/model/term/functionsymbol/db/DBInFunctionSymbol.java
  core/model/src/main/java/it/unibz/inf/ontop/model/term/functionsymbol/db/impl/AbstractDBFunctionSymbolFactory.java
  core/model/src/main/java/it/unibz/inf/ontop/model/term/functionsymbol/db/impl/DBInFunctionSymbolImpl.java
  core/optimization/src/main/java/it/unibz/inf/ontop/injection/impl/OntopOptimizationModule.java
  core/optimization/src/main/java/it/unibz/inf/ontop/iq/optimizer/DisjunctionOfEqualitiesMergingSimplifier.java
  core/optimization/src/main/java/it/unibz/inf/ontop/iq/optimizer/impl/DisjunctionOfEqualitiesMergingSimplifierImpl.java
  core/optimization/src/main/java/it/unibz/inf/ontop/iq/optimizer/impl/GeneralStructuralAndSemanticIQOptimizerImpl.java
  core/optimization/src/main/resources/it/unibz/inf/ontop/injection/optimization-default.properties
  core/optimization/src/test/java/it/unibz/inf/ontop/NoDependencyTestDBMetadata.java
  core/optimization/src/test/java/it/unibz/inf/ontop/iq/optimizer/ConjunctionOfDisjunctionsMergingTest.java
  mapping/core/src/main/java/it/unibz/inf/ontop/spec/mapping/transformer/impl/DefaultMappingTransformer.java
Labels: type: enhancement, type: performance

#759 Propagate foreign keys from basic lenses to parents
  db/rdb/src/main/java/it/unibz/inf/ontop/dbschema/impl/LensMetadataProviderImpl.java
  db/rdb/src/main/java/it/unibz/inf/ontop/dbschema/impl/json/JsonBasicLens.java
  db/rdb/src/main/java/it/unibz/inf/ontop/dbschema/impl/json/JsonLens.java
  db/rdb/src/test/java/it/unibz/inf/ontop/dbschema/BasicLensPropagateFKUpTest.java
  db/rdb/src/test/resources/propagate-fk-up/lenses.json
  db/rdb/src/test/resources/propagate-fk-up/metadata.db-extract.json
Labels: type: enhancement

#761 More non-nullability constraints extracted from the ancestors for transferring self-left-joins based on functional dependencies
  core/optimization/src/main/java/it/unibz/inf/ontop/iq/optimizer/impl/lj/AbstractLJTransformer.java
  core/optimization/src/main/java/it/unibz/inf/ontop/iq/optimizer/impl/lj/CardinalityInsensitiveJoinTransferLJOptimizer.java
  core/optimization/src/main/java/it/unibz/inf/ontop/iq/optimizer/impl/lj/CardinalitySensitiveJoinTransferLJOptimizer.java
  core/optimization/src/main/java/it/unibz/inf/ontop/iq/optimizer/impl/lj/LJWithNestingOnRightToInnerJoinOptimizer.java
  core/optimization/src/test/java/it/unibz/inf/ontop/iq/executor/LeftJoinOptimizationTest.java
Labels: type: enhancement, status: fixed
