Repository ontop/ontop, pull requests merged in 2023-06, with the labels that each got.

#661 Added index type of FlattenNode as LargeInteger
  core/model/src/main/java/it/unibz/inf/ontop/iq/node/impl/FlattenNodeImpl.java
  test/lightweight-tests/src/test/java/it/unibz/inf/ontop/docker/lightweight/AbstractNestedDataTest.java
  test/lightweight-tests/src/test/java/it/unibz/inf/ontop/docker/lightweight/dremio/NestedDataDremioTest.java
  test/lightweight-tests/src/test/java/it/unibz/inf/ontop/docker/lightweight/mssql/NestedDataSQLServerTest.java
  test/lightweight-tests/src/test/resources/nested/athena/nested-lenses-array.json
  test/lightweight-tests/src/test/resources/nested/bigquery/nested-lenses-array.json
  test/lightweight-tests/src/test/resources/nested/dremio/nested-lenses-array.json
  test/lightweight-tests/src/test/resources/nested/spark/nested-lenses-array.json
  test/lightweight-tests/src/test/resources/nested/spark/nested-lenses-json.json
  test/lightweight-tests/src/test/resources/nested/trino/nested-lenses-array.json
Labels: type: enhancement

#660 Implemented SAMPLE DB function symbol to improve performance
  core/model/src/main/java/it/unibz/inf/ontop/model/term/TermFactory.java
  core/model/src/main/java/it/unibz/inf/ontop/model/term/functionsymbol/db/DBFunctionSymbolFactory.java
  core/model/src/main/java/it/unibz/inf/ontop/model/term/functionsymbol/db/impl/AbstractDBFunctionSymbolFactory.java
  core/model/src/main/java/it/unibz/inf/ontop/model/term/functionsymbol/db/impl/DBSampleFunctionSymbolImpl.java
  core/model/src/main/java/it/unibz/inf/ontop/model/term/functionsymbol/db/impl/MockupDBFunctionSymbolFactory.java
  core/model/src/main/java/it/unibz/inf/ontop/model/term/functionsymbol/impl/FunctionSymbolFactoryImpl.java
  core/model/src/main/java/it/unibz/inf/ontop/model/term/functionsymbol/impl/MinBasedSampleSPARQLFunctionSymbol.java
  core/model/src/main/java/it/unibz/inf/ontop/model/term/functionsymbol/impl/MinOrMaxOrSampleSPARQLFunctionSymbolImpl.java
  core/model/src/main/java/it/unibz/inf/ontop/model/term/impl/TermFactoryImpl.java
  db/rdb/src/main/java/it/unibz/inf/ontop/model/term/functionsymbol/db/impl/AbstractSQLDBFunctionSymbolFactory.java
  db/rdb/src/main/java/it/unibz/inf/ontop/model/term/functionsymbol/db/impl/BigQueryDBFunctionSymbolFactory.java
  db/rdb/src/main/java/it/unibz/inf/ontop/model/term/functionsymbol/db/impl/DenodoDBFunctionSymbolFactory.java
  db/rdb/src/main/java/it/unibz/inf/ontop/model/term/functionsymbol/db/impl/DuckDBDBFunctionSymbolFactory.java
  db/rdb/src/main/java/it/unibz/inf/ontop/model/term/functionsymbol/db/impl/OracleDBFunctionSymbolFactory.java
  db/rdb/src/main/java/it/unibz/inf/ontop/model/term/functionsymbol/db/impl/RedshiftDBFunctionSymbolFactory.java
  db/rdb/src/main/java/it/unibz/inf/ontop/model/term/functionsymbol/db/impl/SnowflakeDBFunctionSymbolFactory.java
  db/rdb/src/main/java/it/unibz/inf/ontop/model/term/functionsymbol/db/impl/SparkSQLDBFunctionSymbolFactory.java
  db/rdb/src/main/java/it/unibz/inf/ontop/model/term/functionsymbol/db/impl/TrinoDBFunctionSymbolFactory.java
  test/lightweight-tests/src/test/java/it/unibz/inf/ontop/docker/lightweight/AbstractLeftJoinProfTest.java
  test/lightweight-tests/src/test/java/it/unibz/inf/ontop/docker/lightweight/dremio/NestedDataDremioTest.java
  test/lightweight-tests/src/test/java/it/unibz/inf/ontop/docker/lightweight/oracle/LeftJoinProfOracleTest.java
Labels: type: enhancement, type: performance, status: fixed, w: sparql function

#662 New left join optimisation: reduce the left-join to an inner join in the presence of a left join on the right
  binding/rdf4j/src/test/java/it/unibz/inf/ontop/rdf4j/repository/DestinationTest.java
  binding/rdf4j/src/test/resources/destination/schema.sql
  core/optimization/src/main/java/it/unibz/inf/ontop/iq/optimizer/impl/DefaultCompositeLeftJoinIQOptimizer.java
  core/optimization/src/main/java/it/unibz/inf/ontop/iq/optimizer/impl/lj/LJWithNestingOnRightToInnerJoinOptimizer.java
  core/optimization/src/test/java/it/unibz/inf/ontop/iq/executor/LeftJoinOptimizationTest.java
Labels: type: enhancement, type: performance, status: fixed

#644 QuotedIDFactory refactoring introducing type annotation and lookup by type
  core/model/pom.xml
  core/model/src/main/java/it/unibz/inf/ontop/dbschema/QuotedIDFactory.java
  core/model/src/main/java/it/unibz/inf/ontop/dbschema/impl/QuotedIDImpl.java
  core/model/src/main/java/it/unibz/inf/ontop/dbschema/impl/RawQuotedIDFactory.java
  core/model/src/main/java/it/unibz/inf/ontop/dbschema/impl/SQLStandardQuotedIDFactory.java
  core/model/src/main/java/it/unibz/inf/ontop/injection/impl/OntopAbstractModule.java
  core/model/src/main/java/it/unibz/inf/ontop/injection/impl/OntopModelConfigurationImpl.java
  core/model/src/main/java/it/unibz/inf/ontop/injection/impl/OntopModelModule.java
  core/model/src/test/java/it/unibz/inf/ontop/injection/impl/OntopAbstractModuleTest.java
  core/model/src/test/java/it/unibz/inf/ontop/injection/impl/QuotedIDFactoryInjectionTest.java
  db/rdb/src/main/java/it/unibz/inf/ontop/dbschema/impl/AbstractBacktickQuotedIDFactory.java
  db/rdb/src/main/java/it/unibz/inf/ontop/dbschema/impl/BigQueryQuotedIDFactory.java
  db/rdb/src/main/java/it/unibz/inf/ontop/dbschema/impl/DremioQuotedIDFactory.java
  db/rdb/src/main/java/it/unibz/inf/ontop/dbschema/impl/DuckDBQuotedIDFactory.java
  db/rdb/src/main/java/it/unibz/inf/ontop/dbschema/impl/JsonSerializedMetadataProvider.java
  db/rdb/src/main/java/it/unibz/inf/ontop/dbschema/impl/MySQLAbstractQuotedIDFactory.java
  db/rdb/src/main/java/it/unibz/inf/ontop/dbschema/impl/MySQLCaseNotSensitiveTableNamesQuotedIDFactory.java
  db/rdb/src/main/java/it/unibz/inf/ontop/dbschema/impl/MySQLCaseSensitiveTableNamesQuotedIDFactory.java
  db/rdb/src/main/java/it/unibz/inf/ontop/dbschema/impl/PostgreSQLQuotedIDFactory.java
  db/rdb/src/main/java/it/unibz/inf/ontop/dbschema/impl/SQLServerQuotedIDFactory.java
  db/rdb/src/main/java/it/unibz/inf/ontop/dbschema/impl/SparkSQLQuotedIDFactory.java
  db/rdb/src/main/java/it/unibz/inf/ontop/dbschema/impl/TeiidQuotedIDFactory.java
  db/rdb/src/main/java/it/unibz/inf/ontop/dbschema/impl/TrinoQuotedIDFactory.java
  db/rdb/src/main/java/it/unibz/inf/ontop/dbschema/impl/json/JsonMetadata.java
  db/rdb/src/main/java/it/unibz/inf/ontop/injection/impl/OntopSQLCoreModule.java
  engine/reformulation/core/src/main/java/it/unibz/inf/ontop/injection/impl/OntopReformulationPostModule.java
  pom.xml
  test/lightweight-tests/src/test/java/it/unibz/inf/ontop/docker/lightweight/athena/CastAthenaTest.java
Labels: type: enhancement, status: fixed, w: db support

#663 Merge right children of left-joins nested on the left
  binding/rdf4j/src/test/java/it/unibz/inf/ontop/rdf4j/repository/DestinationTest.java
  binding/rdf4j/src/test/resources/destination/schema.sql
  core/optimization/src/main/java/it/unibz/inf/ontop/iq/optimizer/impl/DefaultCompositeLeftJoinIQOptimizer.java
  core/optimization/src/main/java/it/unibz/inf/ontop/iq/optimizer/impl/lj/LJWithNestingOnRightToInnerJoinOptimizer.java
  core/optimization/src/main/java/it/unibz/inf/ontop/iq/optimizer/impl/lj/MergeLJOptimizer.java
  core/optimization/src/test/java/it/unibz/inf/ontop/OptimizationTestingTools.java
  core/optimization/src/test/java/it/unibz/inf/ontop/iq/executor/LeftJoinOptimizationTest.java
Labels: type: enhancement, type: performance, status: fixed

#664 Make right nested LJ reduction to inner join robust to explicit conditions
  binding/owlapi/src/test/java/it/unibz/inf/ontop/owlapi/MarriageTest.java
  binding/owlapi/src/test/resources/marriage/create-db.sql
  binding/rdf4j/src/test/resources/destination/schema.sql
  core/model/src/main/java/it/unibz/inf/ontop/iq/node/impl/LeftJoinNodeImpl.java
  core/optimization/src/main/java/it/unibz/inf/ontop/iq/optimizer/impl/lj/LJWithNestingOnRightToInnerJoinOptimizer.java
  core/optimization/src/main/java/it/unibz/inf/ontop/iq/optimizer/impl/lj/LeftJoinAnalysisTools.java
  core/optimization/src/main/java/it/unibz/inf/ontop/iq/optimizer/impl/lj/MergeLJOptimizer.java
  core/optimization/src/test/java/it/unibz/inf/ontop/iq/executor/LeftJoinOptimizationTest.java
Labels: type: enhancement, type: performance

#665 Bugfix for issue: Incorrect lifting group-by constants
  binding/rdf4j/src/test/java/it/unibz/inf/ontop/rdf4j/repository/DestinationTest.java
  core/model/src/main/java/it/unibz/inf/ontop/iq/node/normalization/impl/AggregationNormalizerImpl.java
  core/model/src/main/java/it/unibz/inf/ontop/model/term/functionsymbol/db/impl/MockupDBFunctionSymbolFactory.java
  core/optimization/src/test/java/it/unibz/inf/ontop/OptimizationTestingTools.java
  core/optimization/src/test/java/it/unibz/inf/ontop/iq/optimizer/AggregationSplitterTest.java
Labels: type: defect, status: fixed

#667 Join transfer made more robust to non-nullable unique constraints in complex right children
  core/optimization/src/main/java/it/unibz/inf/ontop/iq/optimizer/impl/lj/AbstractJoinTransferLJTransformer.java
  core/optimization/src/main/java/it/unibz/inf/ontop/iq/optimizer/impl/lj/CardinalityInsensitiveJoinTransferLJOptimizer.java
  core/optimization/src/main/java/it/unibz/inf/ontop/iq/optimizer/impl/lj/CardinalitySensitiveJoinTransferLJOptimizer.java
  core/optimization/src/test/java/it/unibz/inf/ontop/iq/executor/LeftJoinOptimizationTest.java
Labels: type: enhancement, type: performance, status: fixed

#669 Supporting dependency between variables when removing non required variables
  core/model/src/main/java/it/unibz/inf/ontop/iq/ConcreteIQTreeCache.java
  core/model/src/main/java/it/unibz/inf/ontop/iq/IQTree.java
  core/model/src/main/java/it/unibz/inf/ontop/iq/impl/AbstractCompositeIQTree.java
  core/model/src/main/java/it/unibz/inf/ontop/iq/impl/BinaryNonCommutativeIQTreeImpl.java
  core/model/src/main/java/it/unibz/inf/ontop/iq/impl/ConcreteIQTreeCacheImpl.java
  core/model/src/main/java/it/unibz/inf/ontop/iq/impl/NaryIQTreeImpl.java
  core/model/src/main/java/it/unibz/inf/ontop/iq/impl/UnaryIQTreeImpl.java
  core/model/src/main/java/it/unibz/inf/ontop/iq/node/BinaryOrderedOperatorNode.java
  core/model/src/main/java/it/unibz/inf/ontop/iq/node/NaryOperatorNode.java
  core/model/src/main/java/it/unibz/inf/ontop/iq/node/UnaryOperatorNode.java
  core/model/src/main/java/it/unibz/inf/ontop/iq/node/impl/AggregationNodeImpl.java
  core/model/src/main/java/it/unibz/inf/ontop/iq/node/impl/ConstructionNodeImpl.java
  core/model/src/main/java/it/unibz/inf/ontop/iq/node/impl/DistinctNodeImpl.java
  core/model/src/main/java/it/unibz/inf/ontop/iq/node/impl/EmptyNodeImpl.java
  core/model/src/main/java/it/unibz/inf/ontop/iq/node/impl/ExtensionalDataNodeImpl.java
  core/model/src/main/java/it/unibz/inf/ontop/iq/node/impl/FilterNodeImpl.java
  core/model/src/main/java/it/unibz/inf/ontop/iq/node/impl/FlattenNodeImpl.java
  core/model/src/main/java/it/unibz/inf/ontop/iq/node/impl/InnerJoinNodeImpl.java
  core/model/src/main/java/it/unibz/inf/ontop/iq/node/impl/IntensionalDataNodeImpl.java
  core/model/src/main/java/it/unibz/inf/ontop/iq/node/impl/JoinLikeNodeImpl.java
  core/model/src/main/java/it/unibz/inf/ontop/iq/node/impl/JoinOrFilterNodeImpl.java
  core/model/src/main/java/it/unibz/inf/ontop/iq/node/impl/LeftJoinNodeImpl.java
  core/model/src/main/java/it/unibz/inf/ontop/iq/node/impl/NativeNodeImpl.java
  core/model/src/main/java/it/unibz/inf/ontop/iq/node/impl/OrderByNodeImpl.java
  core/model/src/main/java/it/unibz/inf/ontop/iq/node/impl/SliceNodeImpl.java
  core/model/src/main/java/it/unibz/inf/ontop/iq/node/impl/TrueNodeImpl.java
  core/model/src/main/java/it/unibz/inf/ontop/iq/node/impl/UnionNodeImpl.java
  core/model/src/main/java/it/unibz/inf/ontop/iq/node/impl/ValuesNodeImpl.java
  core/model/src/main/java/it/unibz/inf/ontop/iq/node/normalization/impl/NotRequiredVariableRemoverImpl.java
  core/model/src/main/java/it/unibz/inf/ontop/iq/request/VariableNonRequirement.java
  core/model/src/main/java/it/unibz/inf/ontop/iq/request/impl/VariableNonRequirementImpl.java
  core/optimization/src/test/java/it/unibz/inf/ontop/iq/executor/LeftJoinOptimizationTest.java
Labels: type: enhancement, type: performance, status: fixed, w: normalization

#668 Propagate Unique Constraints of lenses upwards
  db/rdb/src/main/java/it/unibz/inf/ontop/dbschema/impl/LensMetadataProviderImpl.java
  db/rdb/src/main/java/it/unibz/inf/ontop/dbschema/impl/json/JsonBasicLens.java
  db/rdb/src/main/java/it/unibz/inf/ontop/dbschema/impl/json/JsonLens.java
  db/rdb/src/test/java/it/unibz/inf/ontop/dbschema/BasicLensPropagateUCUpTest.java
  db/rdb/src/test/java/it/unibz/inf/ontop/dbschema/LensParsingTest.java
  db/rdb/src/test/resources/propagate-uc-up/lenses.json
  db/rdb/src/test/resources/propagate-uc-up/metadata.db-extract.json
Labels: type: enhancement, type: performance, status: fixed

#679 Fixed ORDER BY 1 issue for SQLServer
  db/rdb/src/main/java/it/unibz/inf/ontop/generation/serializer/impl/SQLServerSelectFromWhereSerializer.java
  test/docker-tests/src/test/java/it/unibz/inf/ontop/docker/mssql/MsSQLLimitTest.java
Labels: type: defect, status: fixed

#680 Decompose strict equalities with Values nodes
  binding/rdf4j/src/test/java/it/unibz/inf/ontop/rdf4j/repository/DestinationTest.java
  binding/rdf4j/src/test/java/it/unibz/inf/ontop/rdf4j/repository/MirrorViewPersonTest.java
  core/model/src/main/java/it/unibz/inf/ontop/iq/node/impl/ValuesNodeImpl.java
  core/model/src/main/java/it/unibz/inf/ontop/model/term/functionsymbol/db/DBTypeConversionFunctionSymbol.java
  core/model/src/main/java/it/unibz/inf/ontop/model/term/functionsymbol/db/ObjectStringTemplateFunctionSymbol.java
  core/model/src/main/java/it/unibz/inf/ontop/model/term/functionsymbol/db/StringConstantDecomposer.java
  core/model/src/main/java/it/unibz/inf/ontop/model/term/functionsymbol/db/impl/DefaultCastIntegerToStringFunctionSymbol.java
  core/model/src/main/java/it/unibz/inf/ontop/model/term/functionsymbol/db/impl/DefaultSimpleDBCastFunctionSymbol.java
  core/model/src/main/java/it/unibz/inf/ontop/model/term/functionsymbol/db/impl/ObjectStringTemplateFunctionSymbolImpl.java
  core/optimization/src/test/java/it/unibz/inf/ontop/iq/optimizer/ValuesNodeTest.java
Labels: type: enhancement, type: performance, status: fixed, w: normalization

#682 Implemented normalizer for SQLServer that adds an order by clause inside slices
  db/rdb/src/main/java/it/unibz/inf/ontop/generation/normalization/impl/SQLServerExtraNormalizer.java
  db/rdb/src/main/java/it/unibz/inf/ontop/generation/normalization/impl/SQLServerInsertOrderByInSliceNormalizer.java
  db/rdb/src/main/java/it/unibz/inf/ontop/generation/serializer/impl/DefaultSelectFromWhereSerializer.java
  db/rdb/src/main/java/it/unibz/inf/ontop/generation/serializer/impl/SQLServerSelectFromWhereSerializer.java
Labels: type: defect, status: fixed, w: db support

#681 Functional Dependency Inference
  core/model/src/main/java/it/unibz/inf/ontop/iq/ConcreteIQTreeCache.java
  core/model/src/main/java/it/unibz/inf/ontop/iq/IQTree.java
  core/model/src/main/java/it/unibz/inf/ontop/iq/impl/AbstractCompositeIQTree.java
  core/model/src/main/java/it/unibz/inf/ontop/iq/impl/BinaryNonCommutativeIQTreeImpl.java
  core/model/src/main/java/it/unibz/inf/ontop/iq/impl/ConcreteIQTreeCacheImpl.java
  core/model/src/main/java/it/unibz/inf/ontop/iq/impl/NaryIQTreeImpl.java
  core/model/src/main/java/it/unibz/inf/ontop/iq/impl/UnaryIQTreeImpl.java
  core/model/src/main/java/it/unibz/inf/ontop/iq/node/BinaryOrderedOperatorNode.java
  core/model/src/main/java/it/unibz/inf/ontop/iq/node/NaryOperatorNode.java
  core/model/src/main/java/it/unibz/inf/ontop/iq/node/UnaryOperatorNode.java
  core/model/src/main/java/it/unibz/inf/ontop/iq/node/impl/AggregationNodeImpl.java
  core/model/src/main/java/it/unibz/inf/ontop/iq/node/impl/ConstructionNodeImpl.java
  core/model/src/main/java/it/unibz/inf/ontop/iq/node/impl/DistinctNodeImpl.java
  core/model/src/main/java/it/unibz/inf/ontop/iq/node/impl/EmptyNodeImpl.java
  core/model/src/main/java/it/unibz/inf/ontop/iq/node/impl/ExtensionalDataNodeImpl.java
  core/model/src/main/java/it/unibz/inf/ontop/iq/node/impl/FilterNodeImpl.java
  core/model/src/main/java/it/unibz/inf/ontop/iq/node/impl/FlattenNodeImpl.java
  core/model/src/main/java/it/unibz/inf/ontop/iq/node/impl/InnerJoinNodeImpl.java
  core/model/src/main/java/it/unibz/inf/ontop/iq/node/impl/IntensionalDataNodeImpl.java
  core/model/src/main/java/it/unibz/inf/ontop/iq/node/impl/LeftJoinNodeImpl.java
  core/model/src/main/java/it/unibz/inf/ontop/iq/node/impl/NativeNodeImpl.java
  core/model/src/main/java/it/unibz/inf/ontop/iq/node/impl/OrderByNodeImpl.java
  core/model/src/main/java/it/unibz/inf/ontop/iq/node/impl/QueryNodeImpl.java
  core/model/src/main/java/it/unibz/inf/ontop/iq/node/impl/SliceNodeImpl.java
  core/model/src/main/java/it/unibz/inf/ontop/iq/node/impl/TrueNodeImpl.java
  core/model/src/main/java/it/unibz/inf/ontop/iq/node/impl/UnionNodeImpl.java
  core/model/src/main/java/it/unibz/inf/ontop/iq/node/impl/ValuesNodeImpl.java
  core/model/src/main/java/it/unibz/inf/ontop/iq/request/FunctionalDependencies.java
  core/model/src/main/java/it/unibz/inf/ontop/iq/request/impl/FunctionalDependenciesImpl.java
  core/optimization/src/test/java/it/unibz/inf/ontop/DependencyTestDBMetadata.java
  core/optimization/src/test/java/it/unibz/inf/ontop/OptimizationTestingTools.java
  core/optimization/src/test/java/it/unibz/inf/ontop/iq/optimizer/FunctionalDependencyInferenceTest.java
Labels: type: enhancement

#686 Left-join merge made to robust to complex strict-equalities
  binding/rdf4j/src/test/java/it/unibz/inf/ontop/rdf4j/repository/EmployeeTest.java
  core/optimization/src/main/java/it/unibz/inf/ontop/iq/optimizer/impl/lj/ComplexStrictEqualityLeftJoinExpliciter.java
  core/optimization/src/main/java/it/unibz/inf/ontop/iq/optimizer/impl/lj/MergeLJOptimizer.java
  core/optimization/src/test/java/it/unibz/inf/ontop/iq/executor/LeftJoinOptimizationTest.java
Labels: type: enhancement, type: performance, status: fixed

#687 DuckDB metadata refactor
  db/rdb/src/main/java/it/unibz/inf/ontop/dbschema/impl/AbstractDBMetadataProvider.java
  db/rdb/src/main/java/it/unibz/inf/ontop/dbschema/impl/DuckDBDBMetadataProvider.java
  db/rdb/src/main/java/it/unibz/inf/ontop/dbschema/impl/TrinoDBMetadataProvider.java
Labels: type: enhancement, status: fixed, w: db support

#685 Push terms used in substitution below DISTINCT node, if they do not support distinct.
  core/model/src/main/java/it/unibz/inf/ontop/iq/request/FunctionalDependencies.java
  core/model/src/main/java/it/unibz/inf/ontop/iq/request/impl/FunctionalDependenciesImpl.java
  core/model/src/main/java/it/unibz/inf/ontop/model/type/DBTermType.java
  core/model/src/main/java/it/unibz/inf/ontop/model/type/DBTypeFactory.java
  core/model/src/main/java/it/unibz/inf/ontop/model/type/GenericDBTermType.java
  core/model/src/main/java/it/unibz/inf/ontop/model/type/impl/ArrayDBTermType.java
  core/model/src/main/java/it/unibz/inf/ontop/model/type/impl/DBTermTypeImpl.java
  core/model/src/main/java/it/unibz/inf/ontop/model/type/impl/MockupDBTypeFactory.java
  core/optimization/src/main/java/it/unibz/inf/ontop/injection/impl/OntopOptimizationModule.java
  core/optimization/src/main/java/it/unibz/inf/ontop/iq/optimizer/PreventDistinctOptimizer.java
  core/optimization/src/main/java/it/unibz/inf/ontop/iq/optimizer/impl/GeneralStructuralAndSemanticIQOptimizerImpl.java
  core/optimization/src/main/java/it/unibz/inf/ontop/iq/optimizer/impl/PreventDistinctOptimizerImpl.java
  core/optimization/src/main/java/it/unibz/inf/ontop/iq/optimizer/splitter/PreventDistinctProjectionSplitter.java
  core/optimization/src/main/java/it/unibz/inf/ontop/iq/optimizer/splitter/ProjectionSplitter.java
  core/optimization/src/main/java/it/unibz/inf/ontop/iq/optimizer/splitter/impl/PreventDistinctProjectionSplitterImpl.java
  core/optimization/src/main/java/it/unibz/inf/ontop/iq/optimizer/splitter/impl/ProjectionSplitterImpl.java
  core/optimization/src/main/resources/it/unibz/inf/ontop/injection/optimization-default.properties
  core/optimization/src/test/java/it/unibz/inf/ontop/iq/optimizer/PreventDistinctTest.java
  db/rdb/src/main/java/it/unibz/inf/ontop/model/term/functionsymbol/db/impl/BigQueryDBFunctionSymbolFactory.java
  db/rdb/src/main/java/it/unibz/inf/ontop/model/type/impl/BigQueryDBTypeFactory.java
  db/rdb/src/main/java/it/unibz/inf/ontop/model/type/impl/DefaultSQLDBTypeFactory.java
  engine/reformulation/core/src/main/java/it/unibz/inf/ontop/answering/reformulation/generation/PostProcessingProjectionSplitter.java
  engine/reformulation/core/src/main/java/it/unibz/inf/ontop/answering/reformulation/generation/impl/PostProcessingProjectionSplitterImpl.java
  engine/reformulation/sql/src/main/java/it/unibz/inf/ontop/answering/reformulation/generation/impl/SQLGeneratorImpl.java
Labels: type: enhancement, w: db support, w: normalization

#693 Added support for DynamoDB
  db/rdb/src/main/java/it/unibz/inf/ontop/generation/normalization/impl/CDataDynamoDBExtraNormalizer.java
  db/rdb/src/main/java/it/unibz/inf/ontop/generation/normalization/impl/ReformulateConjunctionDisjunctionNormalizer.java
  db/rdb/src/main/java/it/unibz/inf/ontop/generation/serializer/impl/CDataDynamoDBSelectFromWhereSerializer.java
  db/rdb/src/main/java/it/unibz/inf/ontop/model/term/functionsymbol/db/impl/CDataDynamoDBDBFunctionSymbolFactory.java
  db/rdb/src/main/java/it/unibz/inf/ontop/model/term/functionsymbol/db/impl/CDataDynamoDBSQLEncodeURLorIRIFunctionSymbolImpl.java
  db/rdb/src/main/java/it/unibz/inf/ontop/model/type/impl/CDataDynamoDBDBTypeFactory.java
  db/rdb/src/main/resources/it/unibz/inf/ontop/injection/sql-default.properties
  test/lightweight-tests/lightweight-db-test-images/dynamodb/university/course.json
  test/lightweight-tests/lightweight-db-test-images/dynamodb/university/professors.json
  test/lightweight-tests/lightweight-db-test-images/dynamodb/university/teaching.json
  test/lightweight-tests/src/test/java/it/unibz/inf/ontop/docker/lightweight/CDataDynamoDBLightweightTest.java
  test/lightweight-tests/src/test/java/it/unibz/inf/ontop/docker/lightweight/cdatadynamodb/BindWithFunctionsCDataDynamoDBTest.java
  test/lightweight-tests/src/test/java/it/unibz/inf/ontop/docker/lightweight/cdatadynamodb/ConstraintCDataDynamoDBTest.java
  test/lightweight-tests/src/test/java/it/unibz/inf/ontop/docker/lightweight/cdatadynamodb/DistinctInAggregateCDataDynamoDBTest.java
  test/lightweight-tests/src/test/java/it/unibz/inf/ontop/docker/lightweight/cdatadynamodb/LeftJoinProfCDataDynamoDBTest.java
  test/lightweight-tests/src/test/resources/books/cdatadynamodb/books-cdatadynamodb.obda
  test/lightweight-tests/src/test/resources/books/cdatadynamodb/books-cdatadynamodb.properties
  test/lightweight-tests/src/test/resources/dbconstraints/dbconstraints-cdatadynamodb.properties
  test/lightweight-tests/src/test/resources/prof/cdatadynamodb/prof-cdatadynamodb.obda
  test/lightweight-tests/src/test/resources/prof/cdatadynamodb/prof-cdatadynamodb.properties
  test/lightweight-tests/src/test/resources/university/university-cdatadynamodb.obda
  test/lightweight-tests/src/test/resources/university/university-cdatadynamodb.properties
Labels: type: enhancement, status: fixed, w: db support

#695 use all_indexes for unique constraint status
  db/rdb/src/main/java/it/unibz/inf/ontop/dbschema/impl/OracleDBMetadataProvider.java
Labels: type: defect, w: db support
