Repository ontop/ontop, pull requests merged in 2024-01, with the labels that each got.

#782 Update jQuery in endpoint portal
  client/endpoint/src/main/resources/static/jquery.min.js
  client/endpoint/src/main/resources/templates/portal.html
Labels: type: dependency, status: fixed

#783 Self-left-join elimination with nullable determinants of functional dependencies
  core/optimization/src/main/java/it/unibz/inf/ontop/iq/optimizer/impl/lj/DefaultCompositeLeftJoinIQOptimizer.java
  core/optimization/src/main/java/it/unibz/inf/ontop/iq/optimizer/impl/lj/NullableFDSelfLJOptimizer.java
  core/optimization/src/test/java/it/unibz/inf/ontop/OptimizationTestingTools.java
  core/optimization/src/test/java/it/unibz/inf/ontop/iq/executor/LeftJoinOptimizationTest.java
Labels: type: enhancement, status: fixed

#787 Remove redundant MySQL version checks for XSD cast
  .github/workflows/main.yml
  db/rdb/src/main/java/it/unibz/inf/ontop/model/term/functionsymbol/db/impl/MySQLDBFunctionSymbolFactory.java
  test/lightweight-tests/lightweight-db-test-images/docker-compose.lightweight.yml
  test/lightweight-tests/lightweight-db-test-images/mysql/Dockerfile
  test/lightweight-tests/lightweight-db-test-images/mysql/sql/books-mysql.sql
  test/lightweight-tests/src/test/java/it/unibz/inf/ontop/docker/lightweight/mysql/BindWithFunctionsMySQLTest.java
  test/lightweight-tests/src/test/java/it/unibz/inf/ontop/docker/lightweight/mysql/NestedDataMySQLTest.java
Labels: type: defect, status: fixed, w: db support
